### ISSUE TITLE
Speeding up the CI/CD pipeline

### ISSUE THREAD

**Issue by madig** [harfbuzz/uharfbuzz#155]
CI takes too much time to run.

Using ccache in #146 helps some, but not on Windows (need to get it to work there). The following can be a starting point for making ccache work on Windows, also see https://github.com/ccache/ccache/wiki/MS-Visual-Studio:

```toml
[tool.cibuildwheel.windows]
before-all = "choco install ccache"
before-test = "ccache --show-stats"
build-verbosity = 3  # For debugging.

[tool.cibuildwheel.windows.environment]
CC = "ccache.exe cl.exe"
```

The other thing to try is breaking up CI runs into per-platform, per-version. Maybe Cython could also be using the stable Python ABI, so we compile just once for many versions.
